### ISSUE TITLE
Serialization - Implement `Serializer` rather than cloning into `SerializableX`

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint-swc-ecma-ast-view#14]
As title. This would probably be a performance improvement and build on #13.

**Comment by magurotuna** [comment]
@dsherret 
This means we should not use the derive macro `Serialize`, but implement [`Serializer`] trait directly, right?

[`Serializer`]: https://docs.serde.rs/serde/ser/trait.Serializer.html

I didn't come up with it because I only looked into working around the derive macro.
But implementing [`Serializer`] by hand sounds very good for performance!

**Comment by dsherret** [comment]
I'm looking at this more because I need to implement custom serialization for tokens and I'm thinking we shouldn't bother with serde's serialized form agnosticism and instead write out JSON directly. This will allow for more custom serialization.

It looks serde_json::ser::Formatter would be useful https://docs.rs/serde_json/1.0.64/serde_json/ser/trait.Formatter.html (specifically `CompactFormatter`: https://docs.rs/serde_json/1.0.64/serde_json/ser/struct.CompactFormatter.html)

**Comment by dsherret** [comment]
Bit of a monstrosity, but I have this working here for only token serialization: https://github.com/dprint/dprint-swc-ecma-ast-view/blob/c7305802868c0d83a6bff3ca63b6ce433b8b9f7d/generation/generate/generate_serialize.ts#L89
